#!/bin/bash

massiv[0]=zero
massiv[1]=one
massiv[2]=two

for i in {0..2}; do
  echo "${massiv[$i]}"
done

world[0]=15
world[1]=5

world[2]=$((world[0]+world[1]))
echo "${world[2]}"

count=${#massiv[@]}
echo "$count"
