#!/bin/bash

if [[ $1 == "" ]]; then
  read -e -p "Enter filename: " file_name
elif [[ $1 != "" ]]; then
  file_name=$1
fi

if [[ $2 == "" ]]; then
  read -p "Enter file type: C [1] or C++ [2]: " file_type
elif [[ $2 != "" ]]; then
  file_type=$2
fi

if [[ $file_type == 1 ]]; then
  echo "#include <stdio.h>

int main()
{
  /* code */
  return 0;
}" > $file_name.c
  echo "File created."
elif [[ $file_type == 2 ]]; then
  echo "#include <iostream>
using namespace std;

int main()
{
  /* code */
  return 0;
}" > $file_name.cpp
  echo "File created."
else
  echo "Something is wrong!"
fi
