#!/bin/bash

echo "Enter the full link on GitHub"
read -p "-> " full_url

echo "Enter short name of the link"
read -p "-> " link_name

output_link=$(curl -s -i https://git.io -F "url=$full_url" -F "code=$link_name" | grep "Location" | awk '{print $2}')

echo
echo "Your link:"
echo "$output_link"
