#!/bin/bash

# Random Password Generator (RPG)

if [[ $1 == "" || $2 == "" ]]; then
  echo "rpg [passwords_amount] [passwords_characters_long]"
elif [[ $1 != "" && $2 != "" ]]; then
  cat /dev/urandom | tr -dc 'A-Za-z0-9' | fold -w $2 | head -n $1
fi
