#!/bin/bash

if [[ $1 == "" || $2 == "" ]]; then
  echo "wget_downloader [input_file] [download_path]"
  echo ""
  echo "Optional:"
  echo "wget_downloader [input_file] [download_path] --zip [zip_file]"
  echo "wget_downloader [input_file] [download_path] --zip-upload [zip_file]"
elif [[ $1 != "" && $2 != "" ]]; then
  input_file=$1
  download_path=$2

  wget -i $input_file -P $download_path

  sha1sum $download_path/* > $download_path/sha1sum.txt

  if [[ $3 == "--zip" ]]; then
    zip_file=$4

    zip -r $zip_file.zip $download_path
  elif [[ $3 == "--zip-upload" ]]; then
    zip_file=$4

    zip -r $zip_file.zip $download_path

    echo ""
    echo "Link:"
    curl --upload-file ./$zip_file.zip https://transfer.sh/$zip_file.zip
    echo ""
  else
    echo "Something is wrong!"
  fi
fi
